{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "import glob\n",
    "import json\n",
    "import os.path\n",
    "import requests\n",
    "import pandas as pd\n",
    "from  datetime import date"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "today = date.today()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Skipping line 50: expected 4 fields, saw 5\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "               user            instance   \n",
      "0           rheinze        assemblag.es  \\\n",
      "1          BrianJAP      mastodon.world   \n",
      "2       joelglasman     fediscience.org   \n",
      "3  brenton_peterson     sciences.social   \n",
      "4            keremd  social.anoxinon.de   \n",
      "\n",
      "                                           followers            field  \n",
      "0  [109417147220906349, 109243458234695495, 10924...  African Studies  \n",
      "1  [1302832, 110023631275744313, 1099309840163259...  African Studies  \n",
      "2                                                 []  African Studies  \n",
      "3  [107192220324249637, 109354941450990518, 10951...  African Studies  \n",
      "4  [1302832, 109212672053987101, 1092459114371518...  African Studies  \n"
     ]
    }
   ],
   "source": [
    "files = glob.glob('../data/users_followers_*_2023-05-02.csv')\n",
    "all_users = []\n",
    "for file in files:\n",
    "    users = pd.read_csv(file, sep='\\t', names=['user', 'instance', 'followers', 'field'], encoding_errors='replace', on_bad_lines='warn')\n",
    "    all_users.append(users)\n",
    "\n",
    "all_users = pd.concat(all_users)\n",
    "print(all_users.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from requests.adapters import HTTPAdapter\n",
    "from urllib3.util.retry import Retry\n",
    "\n",
    "session = requests.Session()\n",
    "retry = Retry(connect=3, backoff_factor=0.5)\n",
    "adapter = HTTPAdapter(max_retries=retry)\n",
    "session.mount('http://', adapter)\n",
    "session.mount('https://', adapter)\n",
    "\n",
    "\n",
    "def get_userid(user_name, user_server, token_access):\n",
    "    try:\n",
    "        url = 'https://{}/api/v1/accounts/lookup/'.format(user_server)\n",
    "        headers = {\n",
    "            'Authorization' : 'Bearer {}'.format(token_access)\n",
    "        }\n",
    "        params = {\n",
    "            'acct' : '{}@{}'.format(user_name, user_server)\n",
    "        }\n",
    "        r = session.get(url, headers=headers, params=params)\n",
    "\n",
    "        user = json.loads(r.text)\n",
    "        if 'id' in user:\n",
    "            return user[\"id\"]\n",
    "        elif 'user' in user:\n",
    "            return user[\"user\"]\n",
    "    except Exception as error:\n",
    "        print(error)\n",
    "        return None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# mastodon_app = \"acmbrito_app_python_secret\"\n",
    "# client_id, client_secret, access_token, api_base_url = open(mastodon_app).read().split()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "date_limit = date(2022, 9, 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "import util\n",
    "def get_instance_token(instance):\n",
    "    return util.get_instance_token(instance)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "# toots\n",
    "\n",
    "# source to collect user toots: https://jrashford.com/2023/02/13/how-to-scrape-mastodon-timelines-using-python-and-pandas/\n",
    "# API code: https://mastodonpy.readthedocs.io/en/1.8.1/_modules/mastodon/timeline.html?highlight=users%20in%20a%20given%20list\n",
    "# https://docs.joinmastodon.org/methods/search/#v1\n",
    "\n",
    "def user_toots(instance, user_id, access_token):\n",
    "    URL = 'https://{}/api/v1/accounts/{}/statuses'.format(instance, user_id)\n",
    "    user_toots = []\n",
    "    if access_token:\n",
    "        headers = {\n",
    "            'Authorization' : 'Bearer {}'.format(access_token)\n",
    "        }\n",
    "        \n",
    "        user_toots = []\n",
    "        params = {}\n",
    "        while True:\n",
    "            #time.sleep(1)\n",
    "            r = requests.get(URL, headers=headers, params=params, timeout=60)\n",
    "            toots = json.loads(r.text)\n",
    "            user_toots += toots\n",
    "            if len(toots) == 0:\n",
    "                break\n",
    "            if 'error' in toots:\n",
    "                print(user_id, toots)\n",
    "                break\n",
    "            max_id = toots[-1]['id']\n",
    "            params = {'max_id' : max_id}\n",
    "            \n",
    "            date_str = toots[-1]['created_at'].split('T')[0]\n",
    "            last_date = date.fromisoformat(date_str)\n",
    "            if last_date < date_limit:\n",
    "                break\n",
    "\n",
    "    return user_toots"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "valid_fields = ['id',\n",
    "'created_at',\n",
    "'in_reply_to_account_id',\n",
    "'uri',\n",
    "'replies_count',\n",
    "'reblogs_count',\n",
    "'favourites_count',\n",
    "'content'\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "ParserError",
     "evalue": "Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mParserError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[9], line 5\u001b[0m\n\u001b[0;32m      3\u001b[0m invalid_users \u001b[39m=\u001b[39m \u001b[39mset\u001b[39m()\n\u001b[0;32m      4\u001b[0m \u001b[39mfor\u001b[39;00m file \u001b[39min\u001b[39;00m files:\n\u001b[1;32m----> 5\u001b[0m     invalid_users \u001b[39m|\u001b[39m\u001b[39m=\u001b[39m \u001b[39mset\u001b[39m(pd\u001b[39m.\u001b[39;49mread_csv(file, sep\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39m\\t\u001b[39;49;00m\u001b[39m'\u001b[39;49m)[\u001b[39m'\u001b[39m\u001b[39muser_id\u001b[39m\u001b[39m'\u001b[39m])\n\u001b[0;32m      7\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39mlen\u001b[39m(invalid_users))\n",
      "File \u001b[1;32md:\\Documentos\\yy-projects\\mastodon-proj\\.venv\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py:912\u001b[0m, in \u001b[0;36mread_csv\u001b[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)\u001b[0m\n\u001b[0;32m    899\u001b[0m kwds_defaults \u001b[39m=\u001b[39m _refine_defaults_read(\n\u001b[0;32m    900\u001b[0m     dialect,\n\u001b[0;32m    901\u001b[0m     delimiter,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    908\u001b[0m     dtype_backend\u001b[39m=\u001b[39mdtype_backend,\n\u001b[0;32m    909\u001b[0m )\n\u001b[0;32m    910\u001b[0m kwds\u001b[39m.\u001b[39mupdate(kwds_defaults)\n\u001b[1;32m--> 912\u001b[0m \u001b[39mreturn\u001b[39;00m _read(filepath_or_buffer, kwds)\n",
      "File \u001b[1;32md:\\Documentos\\yy-projects\\mastodon-proj\\.venv\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py:583\u001b[0m, in \u001b[0;36m_read\u001b[1;34m(filepath_or_buffer, kwds)\u001b[0m\n\u001b[0;32m    580\u001b[0m     \u001b[39mreturn\u001b[39;00m parser\n\u001b[0;32m    582\u001b[0m \u001b[39mwith\u001b[39;00m parser:\n\u001b[1;32m--> 583\u001b[0m     \u001b[39mreturn\u001b[39;00m parser\u001b[39m.\u001b[39;49mread(nrows)\n",
      "File \u001b[1;32md:\\Documentos\\yy-projects\\mastodon-proj\\.venv\\Lib\\site-packages\\pandas\\io\\parsers\\readers.py:1704\u001b[0m, in \u001b[0;36mTextFileReader.read\u001b[1;34m(self, nrows)\u001b[0m\n\u001b[0;32m   1697\u001b[0m nrows \u001b[39m=\u001b[39m validate_integer(\u001b[39m\"\u001b[39m\u001b[39mnrows\u001b[39m\u001b[39m\"\u001b[39m, nrows)\n\u001b[0;32m   1698\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m   1699\u001b[0m     \u001b[39m# error: \"ParserBase\" has no attribute \"read\"\u001b[39;00m\n\u001b[0;32m   1700\u001b[0m     (\n\u001b[0;32m   1701\u001b[0m         index,\n\u001b[0;32m   1702\u001b[0m         columns,\n\u001b[0;32m   1703\u001b[0m         col_dict,\n\u001b[1;32m-> 1704\u001b[0m     ) \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_engine\u001b[39m.\u001b[39;49mread(  \u001b[39m# type: ignore[attr-defined]\u001b[39;49;00m\n\u001b[0;32m   1705\u001b[0m         nrows\n\u001b[0;32m   1706\u001b[0m     )\n\u001b[0;32m   1707\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m:\n\u001b[0;32m   1708\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mclose()\n",
      "File \u001b[1;32md:\\Documentos\\yy-projects\\mastodon-proj\\.venv\\Lib\\site-packages\\pandas\\io\\parsers\\c_parser_wrapper.py:234\u001b[0m, in \u001b[0;36mCParserWrapper.read\u001b[1;34m(self, nrows)\u001b[0m\n\u001b[0;32m    232\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m    233\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mlow_memory:\n\u001b[1;32m--> 234\u001b[0m         chunks \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_reader\u001b[39m.\u001b[39mread_low_memory(nrows)\n\u001b[0;32m    235\u001b[0m         \u001b[39m# destructive to chunks\u001b[39;00m\n\u001b[0;32m    236\u001b[0m         data \u001b[39m=\u001b[39m _concatenate_chunks(chunks)\n",
      "File \u001b[1;32md:\\Documentos\\yy-projects\\mastodon-proj\\.venv\\Lib\\site-packages\\pandas\\_libs\\parsers.pyx:812\u001b[0m, in \u001b[0;36mpandas._libs.parsers.TextReader.read_low_memory\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32md:\\Documentos\\yy-projects\\mastodon-proj\\.venv\\Lib\\site-packages\\pandas\\_libs\\parsers.pyx:873\u001b[0m, in \u001b[0;36mpandas._libs.parsers.TextReader._read_rows\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32md:\\Documentos\\yy-projects\\mastodon-proj\\.venv\\Lib\\site-packages\\pandas\\_libs\\parsers.pyx:848\u001b[0m, in \u001b[0;36mpandas._libs.parsers.TextReader._tokenize_rows\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32md:\\Documentos\\yy-projects\\mastodon-proj\\.venv\\Lib\\site-packages\\pandas\\_libs\\parsers.pyx:859\u001b[0m, in \u001b[0;36mpandas._libs.parsers.TextReader._check_tokenize_status\u001b[1;34m()\u001b[0m\n",
      "File \u001b[1;32md:\\Documentos\\yy-projects\\mastodon-proj\\.venv\\Lib\\site-packages\\pandas\\_libs\\parsers.pyx:2025\u001b[0m, in \u001b[0;36mpandas._libs.parsers.raise_parser_error\u001b[1;34m()\u001b[0m\n",
      "\u001b[1;31mParserError\u001b[0m: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'."
     ]
    }
   ],
   "source": [
    "files = glob.glob('temp/users_toots_2023-0*.tsv')\n",
    "users_already_collected = []\n",
    "invalid_users = set()\n",
    "for file in files:\n",
    "    invalid_users |= set(pd.read_csv(file, sep='\\t')['user_id'])\n",
    "\n",
    "print(len(invalid_users))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "outputs = []\n",
    "size = 0\n",
    "user_id_map = pd.read_csv('user_id_list.tsv', sep='\\t')\n",
    "user_id_map = user_id_map.drop_duplicates(subset=['user', 'instance'])\n",
    "user_id_map = user_id_map.dropna()\n",
    "\n",
    "for _, user in all_users.iterrows():\n",
    "    \n",
    "    user_id = user_id_map[(user_id_map['user'] == user['user']) & (user_id_map['instance'] == user['instance'])]\n",
    "    if len(user_id) >= 1:\n",
    "        user_id = user_id['user_id'].values[0]\n",
    "    \n",
    "    else:\n",
    "        continue\n",
    "\n",
    "    if not user_id:\n",
    "        print(user)\n",
    "        continue\n",
    "\n",
    "    if not user_id.isnumeric():\n",
    "        continue\n",
    "\n",
    "    if int(user_id) in invalid_users:\n",
    "        continue\n",
    "    \n",
    "    instance_token = get_instance_token(user['instance'])\n",
    "    if not instance_token:\n",
    "        continue\n",
    "\n",
    "    toots = user_toots(user['instance'], user_id, instance_token)\n",
    "    if len(toots) > 0:\n",
    "        toots_pd = pd.json_normalize(toots)\n",
    "        toots_pd = toots_pd.loc[:, valid_fields]\n",
    "        toots_pd['user_id'] = user_id\n",
    "        size += len(toots_pd)\n",
    "        outputs.append(toots_pd)\n",
    "\n",
    "    if size > 10000:\n",
    "        data_toots = pd.concat(outputs)\n",
    "        data_toots.to_csv('temp/users_toots_{}_{}.tsv'.format(today, user_id), sep='\\t')\n",
    "        outputs = []\n",
    "        size = 0\n",
    "\n",
    "data_toots = pd.concat(outputs)\n",
    "data_toots.to_csv('temp/users_toots_{}_{}.tsv'.format(today, user_id), sep='\\t')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#TODO to select instances related to scholars/science\n",
    "#questions: search for scholars on mastodon.social? (the \"main\" instance)\n",
    "\n",
    "# o tamanho de um subconjunto para selecionar?????\n",
    "# fediscience (onde todos os usuarios sao academicos) como primeiro subset\n",
    "# como expandir isso para o mais instancias?\n",
    "# "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ids = []\n",
    "i = 0\n",
    "'''\n",
    "for _, user in all_users.iterrows():\n",
    "    instance_token = get_instance_token(user['instance'])\n",
    "    user_id = get_userid(user['user'], user['instance'], instance_token)\n",
    "    ids.append((user['user'], user['instance'], user_id))\n",
    "    i += 1\n",
    "    if i % 300 == 0:\n",
    "        print(i, end='\\r')\n",
    "        pd.DataFrame(ids, columns=['user', 'instance', 'user_id']).to_csv('user_id_list.tsv', sep='\\t')\n",
    "'''\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['Unnamed: 0', 'mastodon_name'], dtype='object')\n",
      "4677\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>mastodon_name</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>@HelmutBuergmann@mstdn.science</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>@boshek@fosstodon.org</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>@DenisDuboule@mas.to</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>@paulgkeil@mastodon.world</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>@rider_jon@zirk.us</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                    mastodon_name\n",
       "0  @HelmutBuergmann@mstdn.science\n",
       "1           @boshek@fosstodon.org\n",
       "2            @DenisDuboule@mas.to\n",
       "3       @paulgkeil@mastodon.world\n",
       "4              @rider_jon@zirk.us"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filename = '../data/mastodon_users_wOpenAlex.csv'\n",
    "openalex_masto = pd.read_csv(filename, sep=',')\n",
    "print(openalex_masto.columns)\n",
    "openalex_masto = openalex_masto.drop(columns='Unnamed: 0').drop_duplicates()\n",
    "print(openalex_masto.size)\n",
    "openalex_masto.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "HTTPSConnectionPool(host='fediscience.com', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=crisvanhout%40fediscience.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F3840150>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='mastodon.soc', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=siruiwan%40mastodon.soc (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F37C6DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mstdn.scien', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=KeyesDiscovery%40mstdn.scien (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F384F150>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='archeo.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=francescokar%40archeo.social (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F38522D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=fasbrock%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F3868210>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=elinlb%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F384B010>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='sigmoid.soci', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=atchechmedjiev%40sigmoid.soci (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F3869CD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='mastodon.se', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=johanlinaker%40mastodon.se (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1002)')))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mastodon.science', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=mjfave%40mastodon.science (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F388CFD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=Teggy%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F388EB50>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='cryoem.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=susan_lea%40cryoem.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F388C110>, 'Connection to cryoem.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='sbfa.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=minabionta%40sbfa.social (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F388EF50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=arne%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F389C290>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=MRITobi%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F389D2D0>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=jmuncke%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F38800D0>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=trinesy%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F38A92D0>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='social.secret', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=lars%40social.secret (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F38A92D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mastodon.se', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=MartinHedberg%40mastodon.se (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1002)')))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mastdn.science', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=mattloose%40mastdn.science (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)')))\n",
      "HTTPSConnectionPool(host='social.bau', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=aurelvr%40social.bau (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F38C9410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=KevinReuning%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F38C9110>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='fediscience.o', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=cconrymurray%40fediscience.o (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F388EA50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=Claireyjaner%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F38405D0>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=jiatruong%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F38B9790>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mstdn.ai', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=fjlacueva%40mstdn.ai (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F379D710>, 'Connection to mstdn.ai timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='mastodon.aus', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=phillipscate%40mastodon.aus (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F37C4510>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mastadon.energy.', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=donal%40mastadon.energy. (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F37C4D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=sreenathpaleri%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F38B84D0>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=NickCarnes%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F38D9590>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=rgomez%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F38945D0>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='mastadon.energy', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=JustinGundlach%40mastadon.energy (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F48B4590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='mastodon.soci', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=ana_ines_langer%40mastodon.soci (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F48B8310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=jlangemeyer%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F38ADD10>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='ecovo.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=erik_postma%40ecovo.social (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F38D8CD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='mastadon.scot', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=sasM%40mastadon.scot (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F48C0C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='evoeco.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=LuciKirkpatrick%40evoeco.social (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F48BA010>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='ecoevol.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=RyanGutenkunst%40ecoevol.social (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F48CF090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='mastodon.c.im', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=KimNossal%40mastodon.c.im (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F48CF7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='eco.evo.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=kath_baldock%40eco.evo.social (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F49AD7D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 4 (char 3)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mstdn.soc', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=barbarianlibra%40mstdn.soc (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F49BFC50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='evoeco.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=christopher_krieg%40evoeco.social (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F49CCD10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='m.wolfwater.com', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=librarianmer%40m.wolfwater.com (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1002)')))\n",
      "HTTPSConnectionPool(host='m.sclo.nl', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=kimdejong_psychres%40m.sclo.nl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F49D2390>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='mstdn.s', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=ChiaraGamberi%40mstdn.s (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F49E0090>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='fedisciencience.org', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=LarissaGoulart%40fedisciencience.org (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F49D3990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=steffi_nolte%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F49C56D0>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='mastodon.ai', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=shivakjolad%40mastodon.ai (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mastodon.se', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=simonelsasser%40mastodon.se (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1002)')))\n",
      "HTTPSConnectionPool(host='other.nl', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=EricvanHeck%40other.nl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F49E2F50>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='m.sclo.nl', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=christinaisakoglou%40m.sclo.nl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A09590>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='mastodon.uk', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=ela%40mastodon.uk (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1002)')))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=Lenafrescamente%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F4A04410>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='sciences.soc.', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=plieninger%40sciences.soc. (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A27990>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=elizabethlorenc%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F49F7B10>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='mastdodon.online', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=RenseC%40mastdodon.online (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A2E250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mastadon.nz', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=suzewilsonnz%40mastadon.nz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A30110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='ecoevol.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=JasonIsotopes%40ecoevol.social (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A30A10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='social.e', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=aszulinska%40social.e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F49F7DD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='mastodin.sdf', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=greenwoodtree%40mastodin.sdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A24690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='fedicience.org', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=GWeindel%40fedicience.org (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A404D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='twitter.tld', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=MEecoprof%40twitter.tld (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A4EF10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=idelazaro%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F4A527D0>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mathsodon.xyz.', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=Haharrington%40mathsodon.xyz. (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A5C310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='ecoevo.soc', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=kaylakolff%40ecoevo.soc (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A5DC90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=ProfDCotton%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F4A46910>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "HTTPSConnectionPool(host='mastadon.nz', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=RKPriestley%40mastadon.nz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A6DC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='scicomm.cuz', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=tinyfrozenproteins%40scicomm.cuz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A50390>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=clevitan%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F4A41790>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='mastadon.world', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=kayrihavens%40mastadon.world (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A75B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='evoevo.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=MagdaChara%40evoevo.social (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A46C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='genomics.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=vijay%40genomics.social (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A7E190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "HTTPSConnectionPool(host='maston.world', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=ekupers%40maston.world (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000263F4A79410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='weburbanists.com', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=nlowe%40weburbanists.com (Caused by SSLError(CertificateError(\"hostname 'weburbanists.com' doesn't match '139.59.100.39'\")))\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=amandatatts%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F4A77B90>, 'Connection to home.social timed out. (connect timeout=None)'))\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "HTTPSConnectionPool(host='home.social', port=443): Max retries exceeded with url: /api/v1/accounts/lookup/?acct=mptouzel%40home.social (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000263F4A7EAD0>, 'Connection to home.social timed out. (connect timeout=None)'))\n"
     ]
    }
   ],
   "source": [
    "ids = []\n",
    "i = 0\n",
    "\n",
    "for _, user in openalex_masto.iterrows():\n",
    "    mastodon_name = user['mastodon_name'].split(\"@\")[1:]\n",
    "    user_name = mastodon_name[0]\n",
    "    instance_name = mastodon_name[1]\n",
    "    instance_token = get_instance_token(instance_name)\n",
    "    user_id = get_userid(user_name, instance_name, instance_token)\n",
    "    ids.append((user_name, instance_name, user_id))\n",
    "    i += 1\n",
    "    if i % 100 == 0:\n",
    "        print(i, end='\\r')\n",
    "        pd.DataFrame(ids, columns=['user', 'instance', 'user_id']).to_csv('user111_id_list_kunilist_{}.tsv'.format(today), sep='\\t')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Unnamed: 0             user        instance             user_id\n",
      "0          0  HelmutBuergmann   mstdn.science  109290116551935157\n",
      "1          1           boshek   fosstodon.org  109314764090379220\n",
      "2          2     DenisDuboule          mas.to  109258593858933399\n",
      "3          3        paulgkeil  mastodon.world  109500238977329432\n",
      "4          4        rider_jon         zirk.us  109365280591812662\n",
      "108231873383230758 {'error': 'Too many requests'}\n",
      "109252294337269013 {'error': 'Too many requests'}\n",
      "108194402925670785 {'error': 'Too many requests'}\n",
      "312200 {'error': 'Too many requests'}\n",
      "109219602453681496 {'error': 'Too many requests'}\n",
      "109394770510287303 {'error': 'Too many requests'}\n",
      "109244312739228432 {'error': 'Too many requests'}\n",
      "109242396345555512 {'error': 'Too many requests'}\n",
      "108147588127310893 {'error': 'Too many requests'}\n",
      "109248233331530003 {'error': 'Too many requests'}\n",
      "109246123143382012 {'error': 'Too many requests'}\n",
      "109253527096086364 {'error': 'Too many requests'}\n",
      "109372455265699080 {'error': 'Too many requests'}\n",
      "108243570755984490 {'error': 'Too many requests'}\n",
      "270477 {'error': 'Too many requests'}\n",
      "109507760362989414 {'error': 'Too many requests'}\n",
      "109244805624994299 {'error': 'Too many requests'}\n",
      "109490818700975658 {'error': 'Too many requests'}\n",
      "501778 {'error': 'Too many requests'}\n",
      "109258998835390295 {'error': 'Too many requests'}\n",
      "109258550215514313 {'error': 'Too many requests'}\n",
      "109259641320536546 {'error': 'Too many requests'}\n",
      "109248578238524021 {'error': 'Too many requests'}\n",
      "109244105436522718 {'error': 'Too many requests'}\n",
      "140032 {'error': 'Too many requests'}\n",
      "108197573347318141 {'error': 'Too many requests'}\n",
      "108220094526127332 {'error': 'Too many requests'}\n",
      "109246439898736261 {'error': 'Too many requests'}\n",
      "109250552347203385 {'error': 'Too many requests'}\n",
      "1036092 {'error': 'Too many requests'}\n",
      "109251716106943694 {'error': 'Too many requests'}\n",
      "109246059349034462 {'error': 'Too many requests'}\n",
      "109243926293123176 {'error': 'Too many requests'}\n",
      "109259394851576600 {'error': 'Too many requests'}\n",
      "109244618707098765 {'error': 'Too many requests'}\n",
      "109258754451069494 {'error': 'Too many requests'}\n",
      "109255250825869101 {'error': 'Too many requests'}\n",
      "109356090092829726 {'error': 'Too many requests'}\n",
      "235265 {'error': 'Too many requests'}\n",
      "363081 {'error': 'Too many requests'}\n",
      "109208864689604784 {'error': 'Too many requests'}\n",
      "109501199581089749 {'error': 'Too many requests'}\n",
      "109245498416217369 {'error': 'Too many requests'}\n",
      "109362755962378897 {'error': 'Too many requests'}\n",
      "109256445893161075 {'error': 'Too many requests'}\n",
      "109521040564771632 {'error': 'Too many requests'}\n",
      "108197382645989378 {'error': 'Too many requests'}\n",
      "109303621650239942 {'error': 'Too many requests'}\n",
      "503899 {'error': 'Too many requests'}\n",
      "109256535372745343 {'error': 'Too many requests'}\n",
      "491408 {'error': 'Too many requests'}\n",
      "110063187631542285 {'error': 'Too many requests'}\n",
      "108226047470629337 {'error': 'Too many requests'}\n",
      "109245538719694783 {'error': 'Too many requests'}\n",
      "109243388372609150 {'error': 'Too many requests'}\n",
      "109258902341814111 {'error': 'Too many requests'}\n",
      "267944 {'error': 'Too many requests'}\n",
      "37870 {'error': 'Too many requests'}\n",
      "109240273071387835 {'error': 'Too many requests'}\n",
      "109498718146874225 {'error': 'Too many requests'}\n",
      "108245723457268935 {'error': 'Too many requests'}\n",
      "109245369273162229 {'error': 'Too many requests'}\n",
      "108245878016606881 {'error': 'Too many requests'}\n",
      "109242076377424783 {'error': 'Too many requests'}\n",
      "109247807171271369 {'error': 'Too many requests'}\n",
      "109258222978707995 {'error': 'Too many requests'}\n",
      "109246422295487569 {'error': 'Too many requests'}\n",
      "109331776093990272 {'error': 'Too many requests'}\n",
      "15827 {'error': 'Too many requests'}\n",
      "109247432104710610 {'error': 'Too many requests'}\n",
      "109252975695909094 {'error': 'Too many requests'}\n",
      "964265 {'error': 'Too many requests'}\n",
      "109251841864031096 {'error': 'Too many requests'}\n",
      "109312235118077698 {'error': 'Too many requests'}\n",
      "109255969345398096 {'error': 'Too many requests'}\n",
      "108269301093121738 {'error': 'Too many requests'}\n",
      "109898024678328695 {'error': 'Too many requests'}\n",
      "109326729049085482 {'error': 'Too many requests'}\n",
      "108304898201619124 {'error': 'Too many requests'}\n",
      "109243800756872766 {'error': 'Too many requests'}\n",
      "667194 {'error': 'Too many requests'}\n",
      "110225988398635573 {'error': 'Too many requests'}\n"
     ]
    }
   ],
   "source": [
    "outputs = []\n",
    "size = 0\n",
    "user_id_map = pd.read_csv('user111_id_list_kunilist_2023-06-30.tsv', sep='\\t', dtype=object)\n",
    "user_id_map = user_id_map.drop_duplicates(subset=['user', 'instance'])\n",
    "user_id_map = user_id_map.dropna()\n",
    "#user_id_map = user_id_map.astype({'user_id':'int'})\n",
    "print(user_id_map.head())\n",
    "\n",
    "for _, user in user_id_map.iterrows():\n",
    "    '''print(user)\n",
    "    item = user['mastodon_name'].split('@')\n",
    "    \n",
    "    user = {\n",
    "        'user': item[1],\n",
    "        'instance': item[2]\n",
    "    }'''\n",
    "\n",
    "    user_id = user_id_map[(user_id_map['user'] == user['user']) & (user_id_map['instance'] == user['instance'])]\n",
    "    if len(user_id) >= 1:\n",
    "        user_id = user_id['user_id'].values[0]\n",
    "    else:\n",
    "        continue\n",
    "\n",
    "    if not user_id:\n",
    "        print(user)\n",
    "        continue\n",
    "\n",
    "    if not user_id.isnumeric():\n",
    "        continue\n",
    "\n",
    "    # if int(user_id) in invalid_users:\n",
    "    #    continue\n",
    "    \n",
    "    instance_token = get_instance_token(user['instance'])\n",
    "    if not instance_token:\n",
    "        continue\n",
    "\n",
    "    toots = user_toots(user['instance'], user_id, instance_token)\n",
    "    if len(toots) > 0:\n",
    "        toots_pd = pd.json_normalize(toots)\n",
    "        toots_pd = toots_pd.loc[:, valid_fields]\n",
    "        toots_pd['mastodon_name'] = \"{}@{}\".format(user['user'], user['instance']) \n",
    "        size += len(toots_pd)\n",
    "        outputs.append(toots_pd)\n",
    "\n",
    "    if size > 10000:\n",
    "        data_toots = pd.concat(outputs)\n",
    "        data_toots.to_csv('temp/users_toots_{}_{}.tsv'.format(today, user_id), sep='\\t')\n",
    "        outputs = []\n",
    "        size = 0\n",
    "\n",
    "data_toots = pd.concat(outputs)\n",
    "data_toots.to_csv('temp/users_toots_openalex_{}_{}.tsv'.format(today, user_id), sep='\\t')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_toots.to_csv('temp/users_toots_openalex_{}_{}.tsv'.format(today, 'last'), sep='\\t')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Unnamed: 0</th>\n",
       "      <th>user</th>\n",
       "      <th>instance</th>\n",
       "      <th>user_id</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: [Unnamed: 0, user, instance, user_id]\n",
       "Index: []"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "user_id"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "access_token = get_instance_token('home.social')\n",
    "user_id = get_userid('fasbrock', 'home.social', access_token)\n",
    "user_toots('home.social', user_id, access_token)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(user_id)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
